### PR TITLE
Test locally built nats images

### PR DESCRIPTION
**Pull request by ReubenMathew**
I've deleted the old `bench/` directory as part of this PR as well, just to clean stuff up.

### CODE REVIEW

**Comment by ReubenMathew** [comment]
Will add README description and instructions shortly.

**Comment by ReubenMathew** [comment]
Ready for review @mprimi! Try it out yourself and let me know if you run into any problems.

**Comment by mprimi** [comment]
LGTM, should squash commits 1, 3, 4

**Comment by mprimi** [comment]
@ReubenMathew the commits look weird. The first one undoes some stuff i did, then the 3rd one brings it back.

End result looks ok, but there's something off about the way you squashed and/or rebased

**Comment by ReubenMathew** [comment]
> @ReubenMathew the commits look weird. The first one undoes some stuff i did, then the 3rd one brings it back.
> 
> End result looks ok, but there's something off about the way you squashed and/or rebased

Oh ya hmm, I definitely did some unintended stuff. I'm scared to attempt a fix...

**Pull request merged**
